[colors]

black   = #242340
gray    = #313244
white   = #bec7fc
red     = #c34864
green   = #b1dba4
yellow  = #e6dfb8

; Use cases.
background = ${colors.black}
foreground = ${colors.white}
primary = ${colors.white}
alert = ${colors.red}
